//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_master
    {
        public int MT_ID { get; set; }
        public string MT_HN { get; set; }
        public string MT_Fname { get; set; }
        public string MT_Lname { get; set; }
        public string MT_Phone { get; set; }
        public string MT_Email { get; set; }
    }
}
